package cl.model.pojos;
// Generated Apr 8, 2017 9:54:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Componente generated by hbm2java
 */
public class Componente  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nombre;
     private Date fechaCreacion;
     private String creadoPor;
     private String descripcion;
     private Set perfils = new HashSet(0);

    public Componente() {
    }
    
    public Componente(Integer id) {
        this.id = id;
    }
	
    public Componente(Estado estado, String nombre, Date fechaCreacion, String creadoPor) {
        this.estado = estado;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.creadoPor = creadoPor;
    }
    public Componente(Estado estado, String nombre, Date fechaCreacion, String creadoPor, String descripcion, Set perfils) {
       this.estado = estado;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.descripcion = descripcion;
       this.perfils = perfils;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }




}


