package cl.model.pojos;
// Generated Apr 8, 2017 9:54:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set posicionfuncionalperfils = new HashSet(0);
     private Set componentes = new HashSet(0);
     private Set unidadorganizacionals = new HashSet(0);
     private Set posicionfuncionals = new HashSet(0);
     private Set perfils = new HashSet(0);

    public Estado() {
    }
    
    public Estado(int id) {
        this.id = id;
    }

	
    public Estado(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Estado(int id, String nombre, String descripcion, Set posicionfuncionalperfils, Set componentes, Set unidadorganizacionals, Set posicionfuncionals, Set perfils) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.posicionfuncionalperfils = posicionfuncionalperfils;
       this.componentes = componentes;
       this.unidadorganizacionals = unidadorganizacionals;
       this.posicionfuncionals = posicionfuncionals;
       this.perfils = perfils;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPosicionfuncionalperfils() {
        return this.posicionfuncionalperfils;
    }
    
    public void setPosicionfuncionalperfils(Set posicionfuncionalperfils) {
        this.posicionfuncionalperfils = posicionfuncionalperfils;
    }
    public Set getComponentes() {
        return this.componentes;
    }
    
    public void setComponentes(Set componentes) {
        this.componentes = componentes;
    }
    public Set getUnidadorganizacionals() {
        return this.unidadorganizacionals;
    }
    
    public void setUnidadorganizacionals(Set unidadorganizacionals) {
        this.unidadorganizacionals = unidadorganizacionals;
    }
    public Set getPosicionfuncionals() {
        return this.posicionfuncionals;
    }
    
    public void setPosicionfuncionals(Set posicionfuncionals) {
        this.posicionfuncionals = posicionfuncionals;
    }
    public Set getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }




}


