package cl.model.pojos;
// Generated 09/04/2017 08:31:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Matrizcontrolacceso generated by hbm2java
 */
public class Matrizcontrolacceso  implements java.io.Serializable {


     private Integer id;
     private Perfil perfil;
     private Solicitud solicitud;
     private String accion;
     private Date inicio;
     private Date fin;
     private Integer idEjecutor;
     private String estadoSolicitud;
     private int idUsuario;
     private Date fechaAprobacion;
     private Integer idAprobador;
     private Date fechaGestion;
     private Integer idGestor;
     private Date fechaVerificacion;
     private Integer idVerificador;

    public Matrizcontrolacceso() {
    }

	
    public Matrizcontrolacceso(Perfil perfil, Solicitud solicitud, String accion, String estadoSolicitud, int idUsuario) {
        this.perfil = perfil;
        this.solicitud = solicitud;
        this.accion = accion;
        this.estadoSolicitud = estadoSolicitud;
        this.idUsuario = idUsuario;
    }
    public Matrizcontrolacceso(Perfil perfil, Solicitud solicitud, String accion, Date inicio, Date fin, Integer idEjecutor, String estadoSolicitud, int idUsuario, Date fechaAprobacion, Integer idAprobador, Date fechaGestion, Integer idGestor, Date fechaVerificacion, Integer idVerificador) {
       this.perfil = perfil;
       this.solicitud = solicitud;
       this.accion = accion;
       this.inicio = inicio;
       this.fin = fin;
       this.idEjecutor = idEjecutor;
       this.estadoSolicitud = estadoSolicitud;
       this.idUsuario = idUsuario;
       this.fechaAprobacion = fechaAprobacion;
       this.idAprobador = idAprobador;
       this.fechaGestion = fechaGestion;
       this.idGestor = idGestor;
       this.fechaVerificacion = fechaVerificacion;
       this.idVerificador = idVerificador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public Integer getIdEjecutor() {
        return this.idEjecutor;
    }
    
    public void setIdEjecutor(Integer idEjecutor) {
        this.idEjecutor = idEjecutor;
    }
    public String getEstadoSolicitud() {
        return this.estadoSolicitud;
    }
    
    public void setEstadoSolicitud(String estadoSolicitud) {
        this.estadoSolicitud = estadoSolicitud;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }
    
    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }
    public Integer getIdAprobador() {
        return this.idAprobador;
    }
    
    public void setIdAprobador(Integer idAprobador) {
        this.idAprobador = idAprobador;
    }
    public Date getFechaGestion() {
        return this.fechaGestion;
    }
    
    public void setFechaGestion(Date fechaGestion) {
        this.fechaGestion = fechaGestion;
    }
    public Integer getIdGestor() {
        return this.idGestor;
    }
    
    public void setIdGestor(Integer idGestor) {
        this.idGestor = idGestor;
    }
    public Date getFechaVerificacion() {
        return this.fechaVerificacion;
    }
    
    public void setFechaVerificacion(Date fechaVerificacion) {
        this.fechaVerificacion = fechaVerificacion;
    }
    public Integer getIdVerificador() {
        return this.idVerificador;
    }
    
    public void setIdVerificador(Integer idVerificador) {
        this.idVerificador = idVerificador;
    }




}


