package cl.model.pojos;
// Generated Apr 8, 2017 9:54:33 PM by Hibernate Tools 4.3.1



/**
 * Matrizcontrolacceso generated by hbm2java
 */
public class Matrizcontrolacceso  implements java.io.Serializable {


     private Integer id;
     private Estadosolicitud estadosolicitud;
     private Perfil perfil;
     private Solicitud solicitud;
     private String accion;
     private Integer idEjecutor;

    public Matrizcontrolacceso() {
    }

	
    public Matrizcontrolacceso(Estadosolicitud estadosolicitud, Perfil perfil, Solicitud solicitud, String accion) {
        this.estadosolicitud = estadosolicitud;
        this.perfil = perfil;
        this.solicitud = solicitud;
        this.accion = accion;
    }
    public Matrizcontrolacceso(Estadosolicitud estadosolicitud, Perfil perfil, Solicitud solicitud, String accion, Integer idEjecutor) {
       this.estadosolicitud = estadosolicitud;
       this.perfil = perfil;
       this.solicitud = solicitud;
       this.accion = accion;
       this.idEjecutor = idEjecutor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estadosolicitud getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(Estadosolicitud estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Integer getIdEjecutor() {
        return this.idEjecutor;
    }
    
    public void setIdEjecutor(Integer idEjecutor) {
        this.idEjecutor = idEjecutor;
    }




}


