package cl.model.pojos;
// Generated Apr 9, 2017 12:20:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Matrizcontrolacceso generated by hbm2java
 */
public class Matrizcontrolacceso  implements java.io.Serializable {


     private Integer id;
     private Estadosolicitud estadosolicitud;
     private Perfil perfil;
     private Solicitud solicitud;
     private String accion;
     private Date inicio;
     private Date fin;
     private Integer idEjecutor;
     private int idUsuario;

    public Matrizcontrolacceso() {
    }

	
    public Matrizcontrolacceso(Estadosolicitud estadosolicitud, Perfil perfil, Solicitud solicitud, String accion, int idUsuario) {
        this.estadosolicitud = estadosolicitud;
        this.perfil = perfil;
        this.solicitud = solicitud;
        this.accion = accion;
        this.idUsuario = idUsuario;
    }
    public Matrizcontrolacceso(Estadosolicitud estadosolicitud, Perfil perfil, Solicitud solicitud, String accion, Date inicio, Date fin, Integer idEjecutor, int idUsuario) {
       this.estadosolicitud = estadosolicitud;
       this.perfil = perfil;
       this.solicitud = solicitud;
       this.accion = accion;
       this.inicio = inicio;
       this.fin = fin;
       this.idEjecutor = idEjecutor;
       this.idUsuario = idUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estadosolicitud getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(Estadosolicitud estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public Integer getIdEjecutor() {
        return this.idEjecutor;
    }
    
    public void setIdEjecutor(Integer idEjecutor) {
        this.idEjecutor = idEjecutor;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


