package cl.model.pojos;
// Generated Apr 9, 2017 12:49:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private Componente componente;
     private String nombre;
     private Date fechaCreacion;
     private String creadoPor;
     private boolean estado;
     private Set matrizcontrolaccesos = new HashSet(0);
     private Set posicionfuncionalperfils = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(Componente componente, String nombre, Date fechaCreacion, String creadoPor, boolean estado) {
        this.componente = componente;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.creadoPor = creadoPor;
        this.estado = estado;
    }
    public Perfil(Componente componente, String nombre, Date fechaCreacion, String creadoPor, boolean estado, Set matrizcontrolaccesos, Set posicionfuncionalperfils) {
       this.componente = componente;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.estado = estado;
       this.matrizcontrolaccesos = matrizcontrolaccesos;
       this.posicionfuncionalperfils = posicionfuncionalperfils;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getMatrizcontrolaccesos() {
        return this.matrizcontrolaccesos;
    }
    
    public void setMatrizcontrolaccesos(Set matrizcontrolaccesos) {
        this.matrizcontrolaccesos = matrizcontrolaccesos;
    }
    public Set getPosicionfuncionalperfils() {
        return this.posicionfuncionalperfils;
    }
    
    public void setPosicionfuncionalperfils(Set posicionfuncionalperfils) {
        this.posicionfuncionalperfils = posicionfuncionalperfils;
    }




}


