package cl.model.pojos;
// Generated Apr 9, 2017 12:49:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posicionfuncional generated by hbm2java
 */
public class Posicionfuncional  implements java.io.Serializable {


     private Integer id;
     private Unidadorganizacional unidadorganizacional;
     private String nombre;
     private Date fechaCreacion;
     private String creadoPor;
     private boolean estado;
     private Set solicituds = new HashSet(0);
     private Set posicionfuncionalperfils = new HashSet(0);

    public Posicionfuncional() {
    }

	
    public Posicionfuncional(Unidadorganizacional unidadorganizacional, String nombre, Date fechaCreacion, String creadoPor, boolean estado) {
        this.unidadorganizacional = unidadorganizacional;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.creadoPor = creadoPor;
        this.estado = estado;
    }
    public Posicionfuncional(Unidadorganizacional unidadorganizacional, String nombre, Date fechaCreacion, String creadoPor, boolean estado, Set solicituds, Set posicionfuncionalperfils) {
       this.unidadorganizacional = unidadorganizacional;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.estado = estado;
       this.solicituds = solicituds;
       this.posicionfuncionalperfils = posicionfuncionalperfils;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Unidadorganizacional getUnidadorganizacional() {
        return this.unidadorganizacional;
    }
    
    public void setUnidadorganizacional(Unidadorganizacional unidadorganizacional) {
        this.unidadorganizacional = unidadorganizacional;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }
    public Set getPosicionfuncionalperfils() {
        return this.posicionfuncionalperfils;
    }
    
    public void setPosicionfuncionalperfils(Set posicionfuncionalperfils) {
        this.posicionfuncionalperfils = posicionfuncionalperfils;
    }




}


