package cl.model.pojos;
// Generated Apr 9, 2017 12:49:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Posicionfuncionalperfil generated by hbm2java
 */
public class Posicionfuncionalperfil  implements java.io.Serializable {


     private Integer id;
     private Perfil perfil;
     private Posicionfuncional posicionfuncional;
     private Date fechaCreacion;
     private String creadoPor;
     private boolean estado;

    public Posicionfuncionalperfil() {
    }

    public Posicionfuncionalperfil(Perfil perfil, Posicionfuncional posicionfuncional, Date fechaCreacion, String creadoPor, boolean estado) {
       this.perfil = perfil;
       this.posicionfuncional = posicionfuncional;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Posicionfuncional getPosicionfuncional() {
        return this.posicionfuncional;
    }
    
    public void setPosicionfuncional(Posicionfuncional posicionfuncional) {
        this.posicionfuncional = posicionfuncional;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


