package cl.model.pojos;
// Generated 03-abr-2017 15:49:09 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Posicionfuncionalperfil generated by hbm2java
 */
public class Posicionfuncionalperfil  implements java.io.Serializable {


     private PosicionfuncionalperfilId id;
     private Perfil perfil;
     private Posicionfuncional posicionfuncional;
     private Date fechaCreacion;
     private String creadoPor;
     private Estado estado;

    public Posicionfuncionalperfil() {
    }
    
    public Posicionfuncionalperfil(Estado estado, Perfil perfil, Posicionfuncional posicionfuncional, Date fechaCreacion, String creadoPor) {
       this.perfil = perfil;
       this.posicionfuncional = posicionfuncional;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.estado = estado;
    }

    public Posicionfuncionalperfil(Estado estado, PosicionfuncionalperfilId id, Perfil perfil, Posicionfuncional posicionfuncional, Date fechaCreacion, String creadoPor) {
       this.id = id;
       this.perfil = perfil;
       this.posicionfuncional = posicionfuncional;
       this.fechaCreacion = fechaCreacion;
       this.creadoPor = creadoPor;
       this.estado = estado;
    }
   
    public PosicionfuncionalperfilId getId() {
        return this.id;
    }
    
    public void setId(PosicionfuncionalperfilId id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Posicionfuncional getPosicionfuncional() {
        return this.posicionfuncional;
    }
    
    public void setPosicionfuncional(Posicionfuncional posicionfuncional) {
        this.posicionfuncional = posicionfuncional;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    /**
     * @return the estado
     */
    public Estado getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(Estado estado) {
        this.estado = estado;
    }




}


