package cl.model.pojos;
// Generated 03-abr-2017 15:49:09 by Hibernate Tools 4.3.1



/**
 * PosicionfuncionalperfilId generated by hbm2java
 */
public class PosicionfuncionalperfilId  implements java.io.Serializable {


     private int idPosicionFuncional;
     private int idPerfil;

    public PosicionfuncionalperfilId() {
    }

    public PosicionfuncionalperfilId(int idPosicionFuncional, int idPerfil) {
       this.idPosicionFuncional = idPosicionFuncional;
       this.idPerfil = idPerfil;
    }
   
    public int getIdPosicionFuncional() {
        return this.idPosicionFuncional;
    }
    
    public void setIdPosicionFuncional(int idPosicionFuncional) {
        this.idPosicionFuncional = idPosicionFuncional;
    }
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PosicionfuncionalperfilId) ) return false;
		 PosicionfuncionalperfilId castOther = ( PosicionfuncionalperfilId ) other; 
         
		 return (this.getIdPosicionFuncional()==castOther.getIdPosicionFuncional())
 && (this.getIdPerfil()==castOther.getIdPerfil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPosicionFuncional();
         result = 37 * result + this.getIdPerfil();
         return result;
   }   


}


