package cl.model.pojos;
// Generated Apr 9, 2017 12:49:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer id;
     private Posicionfuncional posicionfuncional;
     private Tiposolicitud tiposolicitud;
     private int idSolicitante;
     private Date fechaCreacion;
     private String razon;
     private String observacionAprobador;
     private String observacionAdministrador;
     private String observacionVerificador;
     private String estadoSolicitud;
     private Integer idIntermediario;
     private Set matrizcontrolaccesos = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(Posicionfuncional posicionfuncional, Tiposolicitud tiposolicitud, int idSolicitante, Date fechaCreacion, String estadoSolicitud) {
        this.posicionfuncional = posicionfuncional;
        this.tiposolicitud = tiposolicitud;
        this.idSolicitante = idSolicitante;
        this.fechaCreacion = fechaCreacion;
        this.estadoSolicitud = estadoSolicitud;
    }
    public Solicitud(Posicionfuncional posicionfuncional, Tiposolicitud tiposolicitud, int idSolicitante, Date fechaCreacion, String razon, String observacionAprobador, String observacionAdministrador, String observacionVerificador, String estadoSolicitud, Integer idIntermediario, Set matrizcontrolaccesos) {
       this.posicionfuncional = posicionfuncional;
       this.tiposolicitud = tiposolicitud;
       this.idSolicitante = idSolicitante;
       this.fechaCreacion = fechaCreacion;
       this.razon = razon;
       this.observacionAprobador = observacionAprobador;
       this.observacionAdministrador = observacionAdministrador;
       this.observacionVerificador = observacionVerificador;
       this.estadoSolicitud = estadoSolicitud;
       this.idIntermediario = idIntermediario;
       this.matrizcontrolaccesos = matrizcontrolaccesos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Posicionfuncional getPosicionfuncional() {
        return this.posicionfuncional;
    }
    
    public void setPosicionfuncional(Posicionfuncional posicionfuncional) {
        this.posicionfuncional = posicionfuncional;
    }
    public Tiposolicitud getTiposolicitud() {
        return this.tiposolicitud;
    }
    
    public void setTiposolicitud(Tiposolicitud tiposolicitud) {
        this.tiposolicitud = tiposolicitud;
    }
    public int getIdSolicitante() {
        return this.idSolicitante;
    }
    
    public void setIdSolicitante(int idSolicitante) {
        this.idSolicitante = idSolicitante;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }
    public String getObservacionAprobador() {
        return this.observacionAprobador;
    }
    
    public void setObservacionAprobador(String observacionAprobador) {
        this.observacionAprobador = observacionAprobador;
    }
    public String getObservacionAdministrador() {
        return this.observacionAdministrador;
    }
    
    public void setObservacionAdministrador(String observacionAdministrador) {
        this.observacionAdministrador = observacionAdministrador;
    }
    public String getObservacionVerificador() {
        return this.observacionVerificador;
    }
    
    public void setObservacionVerificador(String observacionVerificador) {
        this.observacionVerificador = observacionVerificador;
    }
    public String getEstadoSolicitud() {
        return this.estadoSolicitud;
    }
    
    public void setEstadoSolicitud(String estadoSolicitud) {
        this.estadoSolicitud = estadoSolicitud;
    }
    public Integer getIdIntermediario() {
        return this.idIntermediario;
    }
    
    public void setIdIntermediario(Integer idIntermediario) {
        this.idIntermediario = idIntermediario;
    }
    public Set getMatrizcontrolaccesos() {
        return this.matrizcontrolaccesos;
    }
    
    public void setMatrizcontrolaccesos(Set matrizcontrolaccesos) {
        this.matrizcontrolaccesos = matrizcontrolaccesos;
    }




}


