package cl.model.pojos;
// Generated Apr 8, 2017 9:54:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer id;
     private Estadosolicitud estadosolicitud;
     private Posicionfuncional posicionfuncional;
     private Tiposolicitud tiposolicitud;
     private String solicitante;
     private Date fechaCreacion;
     private String razon;
     private String observacionAprobador;
     private String observacionAdministrador;
     private String observacionVerificador;
     private Set matrizcontrolaccesos = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(Estadosolicitud estadosolicitud, Posicionfuncional posicionfuncional, Tiposolicitud tiposolicitud, String solicitante, Date fechaCreacion) {
        this.estadosolicitud = estadosolicitud;
        this.posicionfuncional = posicionfuncional;
        this.tiposolicitud = tiposolicitud;
        this.solicitante = solicitante;
        this.fechaCreacion = fechaCreacion;
    }
    public Solicitud(Estadosolicitud estadosolicitud, Posicionfuncional posicionfuncional, Tiposolicitud tiposolicitud, String solicitante, Date fechaCreacion, String razon, String observacionAprobador, String observacionAdministrador, String observacionVerificador, Set matrizcontrolaccesos) {
       this.estadosolicitud = estadosolicitud;
       this.posicionfuncional = posicionfuncional;
       this.tiposolicitud = tiposolicitud;
       this.solicitante = solicitante;
       this.fechaCreacion = fechaCreacion;
       this.razon = razon;
       this.observacionAprobador = observacionAprobador;
       this.observacionAdministrador = observacionAdministrador;
       this.observacionVerificador = observacionVerificador;
       this.matrizcontrolaccesos = matrizcontrolaccesos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estadosolicitud getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(Estadosolicitud estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }
    public Posicionfuncional getPosicionfuncional() {
        return this.posicionfuncional;
    }
    
    public void setPosicionfuncional(Posicionfuncional posicionfuncional) {
        this.posicionfuncional = posicionfuncional;
    }
    public Tiposolicitud getTiposolicitud() {
        return this.tiposolicitud;
    }
    
    public void setTiposolicitud(Tiposolicitud tiposolicitud) {
        this.tiposolicitud = tiposolicitud;
    }
    public String getSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(String solicitante) {
        this.solicitante = solicitante;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }
    public String getObservacionAprobador() {
        return this.observacionAprobador;
    }
    
    public void setObservacionAprobador(String observacionAprobador) {
        this.observacionAprobador = observacionAprobador;
    }
    public String getObservacionAdministrador() {
        return this.observacionAdministrador;
    }
    
    public void setObservacionAdministrador(String observacionAdministrador) {
        this.observacionAdministrador = observacionAdministrador;
    }
    public String getObservacionVerificador() {
        return this.observacionVerificador;
    }
    
    public void setObservacionVerificador(String observacionVerificador) {
        this.observacionVerificador = observacionVerificador;
    }
    public Set getMatrizcontrolaccesos() {
        return this.matrizcontrolaccesos;
    }
    
    public void setMatrizcontrolaccesos(Set matrizcontrolaccesos) {
        this.matrizcontrolaccesos = matrizcontrolaccesos;
    }




}


